### ISSUE TITLE
Readme -  documentation enhancement

### ISSUE THREAD

**Issue by amanBhawsar** [amanBhawsar/PythonScripts#2]

**Comment by TiagoSansao** [comment]
Hello, I don't know exactly the information that you want to put in the README.md, so, I'll make a base to you, and you can easily put the information there, there will be comments to you follow and maintain the stylization. 😃

**Comment by amanBhawsar** [comment]
Yes @TiagoSansao  that would be much better

**Comment by TiagoSansao** [comment]
It's done. #3 
Good luck with your project ^^

**Comment by amanBhawsar** [comment]
Thanks @TiagoSansao 
Could you check [this](https://github.com/amanBhawsar/Coding-Tree/issues/2) also.

**Comment by TiagoSansao** [comment]
@amanBhawsar what do you desire to change? There isn't a description in the link you passed ^^
And sorry to ask, but, is there a way to you put the label "hacktoberfest-accepted." in the previous pull request that I made before? I don't know why, but it didn't count on Hacktoberfest, I'd appreciate a lot if you did this 😃

**Comment by amanBhawsar** [comment]
@TiagoSansao  styling can be added to make it look more attractive. I am not sure but i have referenced this issue with it so it might count now.

**Comment by TiagoSansao** [comment]
@amanBhawsar if you go to the Pull Requests of the project, select the checkbox of mine and select "hacktoberfest-accepted" it'll count ^^ the issue doesn't count, it has to be done in the pull request 👍

Github doesn't allow to use colors in readme.md, can you specify what do you want there? There isn't much stylization to markdown, the best we can do is use emoticons, images, maintain de documentation clean.

**Comment by amanBhawsar** [comment]
@TiagoSansao  Done
